tap "arl/arl"          # for gitmux
tap "derailed/k9s", trusted: true
tap "cloudsmith-io/cloudsmith-cli", trusted: true
tap "containerized-applications/tap", "git@gitlab.aldidevops.com:containerized-applications/homebrew-tap.git", trusted: true

brew "neovim"
brew "zoxide"
brew "television"
brew "tmux"
brew "sesh"
brew "ssh-copy-id"
brew "bat"
brew "eza"
brew "ripgrep"
brew "fd"
brew "fzf"
brew "jq"
brew "yq"
brew "wget"
brew "diff-so-fancy"
brew "mpv"
brew "gitmux"
brew "tree-sitter"
brew "tree-sitter-cli"
brew "stylua"
brew "luarocks"
brew "go"
brew "fnm"
brew "antidote"
brew "azure-cli"
brew "tree"
brew "htop"
brew "httpie"
brew "watch"
brew "rust"
brew "pipx"
brew "glab"
brew "cloudsmith-cli"
brew "shellcheck"
brew "dotnet-sdk"

brew "kubernetes-cli"
brew "minikube"
brew "helm"
brew "helmfile"
brew "derailed/k9s/k9s"
brew "stern"

brew "httpie"
brew "docker"
brew "docker-compose"
brew "docker-buildx"
brew "cmake"

cask "font-jetbrains-mono-nerd-font"

cask "containerized-applications/tap/conapp"

go "github.com/bruderbarna/tms"
