tap "arl/arl"          # for gitmux
tap "derailed/k9s"

brew "neovim"
brew "tmux"
brew "ripgrep"
brew "fd"
brew "fzf"
brew "jq"
brew "yq"
brew "wget"
brew "diff-so-fancy"
brew "mpv"
brew "gitmux"
brew "tree-sitter"
brew "tree-sitter-cli"
brew "stylua"
brew "luarocks"
brew "go"
brew "fnm"
brew "antidote"
brew "azure-cli"
brew "tree"
brew "htop"
brew "httpie"
brew "watch"

brew "kubernetes-cli"
brew "minikube"
brew "helm"
brew "helmfile"
brew "derailed/k9s/k9s"
brew "stern"

brew "httpie"
brew "colima"
brew "docker"
brew "docker-compose"
brew "docker-buildx"
brew "cmake"

# cask "ghostty"
# cask "httpie-desktop"
# cask "postman"
# cask "postman-cli"
# cask "rectangle"
# cask "stats"
# cask "keepingyouawake"
cask "copilot-cli"

cask "font-jetbrains-mono-nerd-font"

tap "containerized-applications/tap"
cask "conapp"
