tap "warrensbox/tap"   # for tfswitch
tap "arl/arl"          # for gitmux

brew "git"
brew "neovim"
brew "tmux"
brew "ripgrep"
brew "fd"
brew "fzf"
brew "jq"
brew "wget"
brew "curl"
brew "diff-so-fancy"
brew "mpv"
brew "bind"
brew "gitmux"
brew "tree-sitter"
brew "stylua"
brew "luarocks"
brew "go"
brew "fnm"
brew "antidote"
brew "azure-cli"
brew "tfswitch"
brew "kubernetes-cli"
brew "helm"

cask "1password"
cask "google-chrome"
cask "ghostty"
cask "intellij-idea"
cask "temurin@21"
cask "vlc"
cask "docker"
cask "neohtop"
cask "microsoft-outlook"
cask "microsoft-teams"

cask "font-jetbrains-mono-nerd-font"
